// Generated by tools/bake_avatar_anim.py sleep -- do not edit by hand.
//
// Keyframes for a sequence composed in the generator from the expressions 'drowsy-closed', 'eyes-closed', sourced from
// deskhog_src/grok-bot-avatar-react/cubee-copy.avatar.json. The generator's geometry
// port is verified byte-identical to the upstream @bible-strong/avatar-core
// renderer.

#pragma once

#include "avatar_face.h"

namespace avatar_face {

// Blended in as the animation's starting pose, matching avatar-core's
// first play. Later loops blend from the previous step instead.
constexpr Pose kSleepNeutral = { 0.0f, 0.0f, 0.0f, 20.0f, 20.0f, 29.983984f, 30.0f, 110.0f, 0.0f, 0.0f, -7.0f, -7.0f, -20.0f, 20.0f, 1.0f };

constexpr Pose kSleepSteps[2] = {
    { 10.2925777f, 3.3992188f, 7.58320332f, 55.6722641f, 55.6722641f, 10.0f, 10.0f, 143.416794f, 0.0f, 0.0f, 0.0f, 0.0f, -20.0f, 20.0f, 1.0f },  // drowsy-closed
    { -8.75234413f, -8.74335957f, -10.7738285f, 56.1339836f, 56.1339836f, 10.0f, 10.0f, 144.276169f, 0.0f, 0.0f, 0.0f, 0.0f, -20.0f, 20.0f, 1.0f },  // eyes-closed
};

constexpr uint16_t kSleepHolds[2] = { 4000, 4000 };

// screen_x = screen_cx + scale * (proj_x - view_cx)
// screen_y = screen_cy + scale * (proj_y - view_cy)
// `scale` is the largest factor that keeps the whole loop on the panel
// with a 4 px margin.
constexpr Anim kSleep = {
    { kSurfaceCube, 120.0f, 67.5f, 75.0f, 7.14285714f },  // surface: cube
    kSleepSteps,
    kSleepHolds,
    kSleepNeutral,
    2,      // step_count
    1600,      // transition_ms
    0,     // blink_initial_delay_ms
    0,     // blink_min_interval_ms
    0,     // blink_max_interval_ms
    0,      // blink_duration_ms
    0.3f,  // corner: eye corner radius / capsule radius
    0.45f,  // travel: fraction of the projected eye motion kept
    20.0f,  // spread: extra eye separation, device px
    1.11281268f,  // scale
    -0.333809501f,  // view_cx
    3.64226468f,  // view_cy
    120.0f,  // screen_cx
    67.5f,   // screen_cy
    64,      // canvas_w
    45,      // canvas_h
};

// Measured over the whole loop; the shared buffers must cover them.
static_assert(146 <= kMaxOutlinePoints, "raise kMaxOutlinePoints");
static_assert(64 <= kMaxCanvasW, "raise kMaxCanvasW");
static_assert(45 <= kMaxCanvasH, "raise kMaxCanvasH");

}  // namespace avatar_face
