// Generated by tools/bake_avatar_anim.py done -- do not edit by hand.
//
// Keyframes for a sequence composed in the generator from the expressions 'joyful-down-right', 'curious-left', 'playful-right', sourced from
// deskhog_src/grok-bot-avatar-react/cubee-copy.avatar.json. The generator's geometry
// port is verified byte-identical to the upstream @bible-strong/avatar-core
// renderer.

#pragma once

#include "avatar_face.h"

namespace avatar_face {

// Blended in as the animation's starting pose, matching avatar-core's
// first play. Later loops blend from the previous step instead.
constexpr Pose kDoneNeutral = { 0.0f, 0.0f, 0.0f, 20.0f, 20.0f, 29.983984f, 30.0f, 110.0f, 0.0f, 0.0f, -7.0f, -7.0f, -20.0f, 20.0f, 1.0f };

constexpr Pose kDoneSteps[3] = {
    { -15.2871094f, 15.0066404f, 12.7878904f, 31.2539062f, 31.2539062f, 56.704689f, 56.7207031f, 143.699997f, 0.0f, 0.0f, 0.0f, 0.0f, -20.0f, 20.0f, 1.0f },  // joyful-down-right
    { -12.3035154f, -17.6011715f, 5.91093731f, 20.6058598f, 20.6058598f, 27.7539062f, 27.7699223f, 129.899994f, 0.0f, 0.0f, 0.0f, 0.0f, 3.52304697f, -4.04257822f, 1.0f },  // curious-left
    { -4.39531231f, 14.0726566f, -16.1261711f, 19.045145f, 19.045145f, 23.3546867f, 23.3707027f, 126.731247f, 0.0f, 0.0f, 0.0f, 0.0f, 6.29218769f, -0.249218747f, 1.0f },  // playful-right
};

constexpr uint16_t kDoneHolds[3] = { 600, 600, 600 };

// screen_x = screen_cx + scale * (proj_x - view_cx)
// screen_y = screen_cy + scale * (proj_y - view_cy)
// `scale` is the largest factor that keeps the whole loop on the panel
// with a 4 px margin.
constexpr Anim kDone = {
    { kSurfaceCube, 120.0f, 67.5f, 75.0f, 7.14285714f },  // surface: cube
    kDoneSteps,
    kDoneHolds,
    kDoneNeutral,
    3,      // step_count
    300,      // transition_ms
    1200,     // blink_initial_delay_ms
    1800,     // blink_min_interval_ms
    3600,     // blink_max_interval_ms
    220,      // blink_duration_ms
    0.3f,  // corner: eye corner radius / capsule radius
    0.5f,  // travel: fraction of the projected eye motion kept
    20.0f,  // spread: extra eye separation, device px
    1.11768525f,  // scale
    4.7186545f,  // view_cx
    16.5844409f,  // view_cy
    120.0f,  // screen_cx
    67.5f,   // screen_cy
    57,      // canvas_w
    76,      // canvas_h
};

// Measured over the whole loop; the shared buffers must cover them.
static_assert(158 <= kMaxOutlinePoints, "raise kMaxOutlinePoints");
static_assert(57 <= kMaxCanvasW, "raise kMaxCanvasW");
static_assert(76 <= kMaxCanvasH, "raise kMaxCanvasH");

}  // namespace avatar_face
