// Generated by tools/bake_avatar_anim.py idle -- do not edit by hand.
//
// Keyframes for the 'idle-two' animation, sourced from
// deskhog_src/grok-bot-avatar-react/cubee-copy.avatar.json. The generator's geometry
// port is verified byte-identical to the upstream @bible-strong/avatar-core
// renderer.

#pragma once

#include "avatar_face.h"

namespace avatar_face {

// Blended in as the animation's starting pose, matching avatar-core's
// first play. Later loops blend from the previous step instead.
constexpr Pose kIdleNeutral = { 0.0f, 0.0f, 0.0f, 20.0f, 20.0f, 29.983984f, 30.0f, 110.0f, 0.0f, 0.0f, -7.0f, -7.0f, -20.0f, 20.0f, 1.0f };

constexpr Pose kIdleSteps[2] = {
    { 0.0f, 10.0f, -16.1000004f, 22.5011711f, 22.5011711f, 22.3617191f, 22.3777351f, 129.300003f, 0.0f, 0.0f, -20.5f, -20.5f, -20.0f, 20.0f, 1.0f },  // upward-side-glance
    { -12.3035154f, -17.6011715f, 5.91093731f, 20.6058598f, 20.6058598f, 27.7539062f, 27.7699223f, 129.899994f, 0.0f, 0.0f, 0.0f, 0.0f, 3.52304697f, -4.04257822f, 1.0f },  // curious-left
};

constexpr uint16_t kIdleHolds[2] = { 5200, 5200 };

// screen_x = screen_cx + scale * (proj_x - view_cx)
// screen_y = screen_cy + scale * (proj_y - view_cy)
// `scale` is the largest factor that keeps the whole loop on the panel
// with a 4 px margin.
constexpr Anim kIdle = {
    { kSurfaceCube, 120.0f, 67.5f, 75.0f, 7.14285714f },  // surface: cube
    kIdleSteps,
    kIdleHolds,
    kIdleNeutral,
    2,      // step_count
    500,      // transition_ms
    2600,     // blink_initial_delay_ms
    3400,     // blink_min_interval_ms
    6200,     // blink_max_interval_ms
    280,      // blink_duration_ms
    0.3f,  // corner: eye corner radius / capsule radius
    0.62f,  // travel: fraction of the projected eye motion kept
    20.0f,  // spread: extra eye separation, device px
    1.27497838f,  // scale
    -8.28992883f,  // view_cx
    -6.98856006f,  // view_cy
    120.0f,  // screen_cx
    67.5f,   // screen_cy
    40,      // canvas_w
    52,      // canvas_h
};

// Measured over the whole loop; the shared buffers must cover them.
static_assert(116 <= kMaxOutlinePoints, "raise kMaxOutlinePoints");
static_assert(40 <= kMaxCanvasW, "raise kMaxCanvasW");
static_assert(52 <= kMaxCanvasH, "raise kMaxCanvasH");

}  // namespace avatar_face
