// Generated by tools/bake_avatar_anim.py working -- do not edit by hand.
//
// Keyframes for the 'thinking-two-ani' animation, sourced from
// deskhog_src/grok-bot-avatar-react/cubee-copy.avatar.json. The generator's geometry
// port is verified byte-identical to the upstream @bible-strong/avatar-core
// renderer.

#pragma once

#include "avatar_face.h"

namespace avatar_face {

// Blended in as the animation's starting pose, matching avatar-core's
// first play. Later loops blend from the previous step instead.
constexpr Pose kWorkingNeutral = { 0.0f, 0.0f, 0.0f, 20.0f, 20.0f, 29.983984f, 30.0f, 110.0f, 0.0f, 0.0f, -7.0f, -7.0f, -20.0f, 20.0f, 1.0f };

constexpr Pose kWorkingSteps[6] = {
    { 0.0f, 10.0f, -16.1000004f, 22.5011711f, 22.5011711f, 22.3617191f, 22.3777351f, 129.300003f, 0.0f, 0.0f, -20.5f, -20.5f, -20.0f, 20.0f, 1.0f },  // upward-side-glance
    { 0.0f, 0.0f, 9.0f, 20.0f, 50.0f, 49.9839859f, 10.0f, 131.300003f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -20.0f, 1.0f },  // thinking-three
    { 0.0f, 0.0f, 5.0f, 51.7999992f, 51.7999992f, 10.0f, 10.0f, 138.872269f, 0.0f, 0.0f, 0.0f, 0.0f, 15.0f, -15.0f, 1.0f },  // working-1
    { -14.7507811f, -19.3500004f, 5.63164043f, 19.6023445f, 19.6023445f, 28.6238289f, 28.639843f, 130.100006f, 0.0f, 0.0f, 0.0f, 0.0f, -47.6066399f, 46.1484375f, 1.0f },  // angry-left
    { -5.4281249f, -11.7132816f, -13.4722652f, 51.4000015f, 50.5f, 30.0839844f, 29.3999996f, 144.0f, 0.0f, 0.0f, 0.0f, 0.0f, -20.0f, 20.0f, 1.0f },  // surprised-wide-left
    { -17.1277351f, 18.0707035f, 13.8917971f, 35.4527359f, 35.4527359f, 59.0882797f, 59.1042976f, 145.800003f, 0.0f, 0.0f, 0.0f, 0.0f, -20.0f, 20.0f, 1.0f },  // wide-down-left
};

constexpr uint16_t kWorkingHolds[6] = { 2000, 3000, 3000, 3000, 3000, 3000 };

// screen_x = screen_cx + scale * (proj_x - view_cx)
// screen_y = screen_cy + scale * (proj_y - view_cy)
// `scale` is the largest factor that keeps the whole loop on the panel
// with a 4 px margin.
constexpr Anim kWorking = {
    { kSurfaceCube, 120.0f, 67.5f, 75.0f, 7.14285714f },  // surface: cube
    kWorkingSteps,
    kWorkingHolds,
    kWorkingNeutral,
    6,      // step_count
    500,      // transition_ms
    1500,     // blink_initial_delay_ms
    3400,     // blink_min_interval_ms
    6200,     // blink_max_interval_ms
    280,      // blink_duration_ms
    0.3f,  // corner: eye corner radius / capsule radius
    0.62f,  // travel: fraction of the projected eye motion kept
    20.0f,  // spread: extra eye separation, device px
    1.00647222f,  // scale
    1.85952466f,  // view_cx
    6.2983305f,  // view_cy
    120.0f,  // screen_cx
    67.5f,   // screen_cy
    55,      // canvas_w
    71,      // canvas_h
};

// Measured over the whole loop; the shared buffers must cover them.
static_assert(164 <= kMaxOutlinePoints, "raise kMaxOutlinePoints");
static_assert(55 <= kMaxCanvasW, "raise kMaxCanvasW");
static_assert(71 <= kMaxCanvasH, "raise kMaxCanvasH");

}  // namespace avatar_face
